name: education
description: An app build with the stacked framework

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  step_progress_indicator: ^1.0.2
  flutter_switch: ^0.3.2
  flutter_snake_navigationbar: ^0.6.1
  table_calendar: ^3.0.8
  comment_box: ^0.0.18
  syncfusion_flutter_sliders: ^20.4.54
  chips_choice: ^3.0.0
  flutter_feather_icons: ^2.0.0+1
  calender_picker: ^1.0.7
  flutter_credit_card: ^3.0.6
  pin_code_fields: ^7.4.0
  numeric_keyboard: ^1.1.0
  lottie: ^2.3.0
  flutter_svg: ^2.0.4
  syncfusion_flutter_charts: ^20.4.54
  readmore: ^2.2.0
  video_player: ^2.6.0
  flutter_rating_bar: ^4.0.1
  local_auth: ^2.1.6
  carousel_slider: ^4.2.1
  pinput: ^2.2.31
  flip: ^2.0.0
  flip_card: ^0.7.0
  calendar_date_picker2: ^0.5.2
  fl_chart: ^0.62.0
  
  stacked: ^3.2.7
  stacked_services: ^1.0.0
  email_auth: ^0.0.1+2
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.2
  email_otp: ^2.0.1
  shared_preferences:
  loading_animation_widget: ^1.2.0+4
  timeago: ^3.3.0
  cached_network_image: ^3.0.0
  syncfusion_flutter_pdfviewer: ^20.4.54
  file_picker: ^5.5.0
  pdf_viewer_plugin: ^2.0.1
  firebase_crashlytics: ^3.4.5
  camera: ^0.10.5+5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0

  stacked_generator: ^1.0.0
  mockito: ^5.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700


