// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvzrjG9LIlLuMRgl7Sr6FDrYhRejkbGM',
    appId: '1:296138001275:web:1477a6e888e432e67d8bde',
    messagingSenderId: '296138001275',
    projectId: 'flutter-signup-login-app',
    authDomain: 'flutter-signup-login-app.firebaseapp.com',
    storageBucket: 'flutter-signup-login-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFt9rfagvcgwcJu2R7DFizFqBEztxsrWg',
    appId: '1:296138001275:android:2bd2fd3b36ead7177d8bde',
    messagingSenderId: '296138001275',
    projectId: 'flutter-signup-login-app',
    storageBucket: 'flutter-signup-login-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJo7kEhJt720EZEB_QyvbhxvwXNJzjez8',
    appId: '1:296138001275:ios:01983bc61ed469777d8bde',
    messagingSenderId: '296138001275',
    projectId: 'flutter-signup-login-app',
    storageBucket: 'flutter-signup-login-app.appspot.com',
    iosBundleId: 'com.example.loginSignupFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJo7kEhJt720EZEB_QyvbhxvwXNJzjez8',
    appId: '1:296138001275:ios:c0a3e93ad55d3eb47d8bde',
    messagingSenderId: '296138001275',
    projectId: 'flutter-signup-login-app',
    storageBucket: 'flutter-signup-login-app.appspot.com',
    iosBundleId: 'com.example.loginSignupFirebase.RunnerTests',
  );
}
